name: Deploy Python app to Azure Web App - HireVell-AI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D6868731433241C1B772FF65DDC9D594 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_71024B08022441AAB3AA6D4447071F53 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AF1083A0745C40B682AC3B9644235D4E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HireVell-AI'
          slot-name: 'Production'
          package: .
          startup-command: 'gunicorn --bind=0.0.0.0:${PORT} main_test:app'
